// @generated by protoc-gen-connect-web v0.11.0 with parameter "target=js"
// @generated from file test_server_interface/v1/test/test.proto (package test.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetTestDataRequest, Notification, SubscribeRequest, TestData } from "./test_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service test.v1.TestService
 */
export const TestService = {
  typeName: "test.v1.TestService",
  methods: {
    /**
     * @generated from rpc test.v1.TestService.Subscribe
     */
    subscribe: {
      name: "Subscribe",
      I: SubscribeRequest,
      O: Notification,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc test.v1.TestService.GetTestData
     */
    getTestData: {
      name: "GetTestData",
      I: GetTestDataRequest,
      O: TestData,
      kind: MethodKind.Unary,
    },
  }
};

