// @generated by protoc-gen-es v1.3.0 with parameter "target=js"
// @generated from file test_server_interface/v1/test/test.proto (package test.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message test.v1.SubscribeRequest
 */
export const SubscribeRequest = proto3.makeMessageType(
  "test.v1.SubscribeRequest",
  [],
);

/**
 * @generated from message test.v1.Notification
 */
export const Notification = proto3.makeMessageType(
  "test.v1.Notification",
  () => [
    { no: 1, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message test.v1.GetTestDataRequest
 */
export const GetTestDataRequest = proto3.makeMessageType(
  "test.v1.GetTestDataRequest",
  () => [
    { no: 1, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message test.v1.TestData
 */
export const TestData = proto3.makeMessageType(
  "test.v1.TestData",
  () => [
    { no: 1, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

